const puppeteer = require('puppeteer');
const { faker } = require('@faker-js/faker');

const namaPendek = [
  "Aini Fadia Ifra",
  "Amanda Syamilla Balqis",
  "Aristi Bayu Kurniawati",
  "Ashfa Annaida Ummaya",
  "Dahlia Intan Nur Hikmah",
  "Hanifatuz Zahro",
  "Rima Nur Rahmawati",
  "Serly Arum Lestari",
  "Uyun Salsabila",
  "Almaira Ananda Fika",
  "Annisa Rahmawati",
  "Apriza Nur'aeni",
  "Azka Nabila",
  "Dinara Safina Putri Haryanto",
  "Eko Sapto Nugroho",
  "Nadine Zaneta Putri",
  "Rahmah Putri Artanti",
  "Rizka Wijayanti",
  "Siti Kholifah",
  "Tasya Aprilliani P",
  "Amin Arga Kusuma",
  "Anggun Lavina Fajarrina",
  "Ayla Nazma",
  "Desty Wulandari",
  "Jamilah Eka Maharani",
  "Lu'lu' Syaikhoh",
  "Syifa Aura Ramadhanti",
  "Vanesa Juliana Putri Anjani",
  "Aldian Fandy Nugraha",
  "Alsya Rizka Kamila",
  "Bagus Maulana Saputra",
  "Gigih Praditya",
  "Kamila Az Zahra",
  "Khevaldo Apriansyah",
  "Livia Adiska Maulida",
  "Maylani Azzahro",
  "Muhamad Surya Fattah",
  "Naya Setyaning Wigati",
  "Ristia Evi Safitri",
  "Rizal Faiq Tsani Al Kaafi",
  "Rizki Tri Yulianti",
  "Sofi Rahmaningsih",
  "Zahwa Akkila",
  "Bima Pranata",
  "Devita Oktavia",
  "Febrisa Heti Putri Wulandari",
  "Khalisha Farrasa Ramadhani",
  "Merlin Amelia Nainel",
  "Muhammad Fahmi Sidik",
  "Rauf Dian Iswara",
  "Resti Ramadina",
  "Safadilla Nur'aini",
  "Salsabilla Khoirunnisa",
  "Umal Janatul Hariyah",
  "Utami Agustanti",
  "Zulia Puspita Sari",
  "Adellia Anggreani",
  "Desi Anggreani",
  "Diah Fitrotul 'Izzah",
  "Fa'if Hestri Musdyawati",
  "Fairuz Husna",
  "Husna Nabila Azra",
  "Iis Setiya Ningsih",
  "Rangga Prawira Nugraha",
  "Sawijiati",
  "Sylviana Nur Ramadhani",
  "Vivian Putri Natasya",
  "Wahyu Fitran Pradana",
  "Bagus Setiawan",
  "Daffa Khoiron Nu'man",
  "Defort Da Pinta Palintu",
  "Naila Rizqi Oktafia",
  "Nur Oktavia",
  "Rizqi Jihan Umniatun",
  "Sakya Keisha Reena Pitra",
  "Saroh Tusita",
  "Syurfannaja Tanjali",
  "Ikhvan Lutfianur",
  "Risma Damayanti",
  "Silfia Rahma Dani",
  "Uti Utami Ningsih",
  "Yunita Tri Rahayu",
  "Ayuanita Rosandra",
  "Binti Ma'Rifatun",
  "Akhmad Ujang Alviansyah",
  "Dynda Bagoes Silvina",
  "Indah Ayu Setyaningsih",
  "Khotimatun Husna",
  "Mentari Putri",
  "Rahman Dani",
  "Reihan Nanda Prasetya",
  "Risky Kurniawan",
  "Sri Rakhmawati Kurnianingsih",
  "Syifaaul Jannah",
  "Avifah Nashya Tia Fadillah",
  "Felita Indah Oktafitriani",
  "Ika Nurya Sabila",
  "Khansaa Nisa Herdiansyah",
  "Resti Aprilia Nitasari",
  "Satriyo Dexa Saputra",
  "Sofyan Arya Hendrawan",
  "Tri Wahyu Ningsih",
  "Verlyta Eyleen Agatha",
  "Intan Lestari Ayu Puspitha",
  "Nurlita Widyawati",
  "Rezky Mirza Alfathi",
  "Rifqi Yudha Satria",
  "Ghani Kastuba",
  "Hafizh Naufal Fiyandika",
  "Muhammad Nabil Fahreza",
  "Wildan Athoul Maula",
  "Anggi Galih Cadhika",
  "Arga Pradana",
  "Ashilah Khansa Brilliana",
  "Fina Salsabila Auliya Putri",
  "Komala Sari",
  "Rizqi Miftakhul Ibad",
  "Vian Dwi Andika",
  "Gendis Widhiya Lestari",
  "Novia Alifta",
  "Areta Imalia",
  "Wisnu Budi Utomo",
  "Difa Luthfia Zahra",
  "Muh. Haidar Dliyaul Haq",
  "Belva Bintang Prayogatama",
  "Dema Herliana Dewi",
  "Hendru",
  "Muhammad Fahmi Ngulumaddin",
  "Najwa Raiya Refani",
  "Arum Kinasih",
  "Fajar Bakti Tri Kusuma",
  "Kaila Akila Azzahra",
  "Desty Wulandari",
  "Lu’lu Syaikhoh",
  "Nisrinaa",
  "Nur Maulida Kamila",
  "Alsya Rizka Kamila",
  "Mahesa Dika Pamungkas",
  "Maylani Azzahro",
  "Gigih Praditya",
  "Ahnaf Kaifiat Pradana",
  "Arya Bimantara Ramadhan",
  "Raditya Bagaskara",
  "Restiramadina",
  "Salsabilla Khoirunnisa",
  "Aryanto Wibowo",
  "Muhammad Ilham Ramadhan",
  "Riska Setiarini",
  "Sylviana Nur Ramadhani",
  "Annisah Az Zahra",
  "Bagus Setiawan",
  "Daffa Khoirun Nu’man",
  "Deffort Da Pinta Palintu",
  "Muhammad Khoirul Umam",
  "Muhammad Yusa Saputra",
  "Idha Muflihatun Ngarofah",
  "Ikhvan Lutfianur",
  "Mahdah Nur Cahyani",
  "Meike Nur Janah",
  "Muhammad Andika Fathir",
  "Putri Robi Aal Adawiyah",
  "Bimo Dafa Exel Pratama",
  "Venty Ristiyana Dewi",
  "Angga Yuli Prasetyo",
  "Anggie Khowiyatun Fikaya",
  "Fasihatul Huda Khoyrunnisa",
  "Muhammad Naufal Azamy",
  "Silvia Nur Rokhmah",
  "Azka Nabila",
  "Rafif Sawlsa Samahita",
  "Sinta Agustina",
  "Mustika Sania Rohmah",
  "Novi Aulia Habiela",
  "Amelia Herdianingsih",
  "Desti Aulia Oktafiana",
  "Nazimah Nur 'Azizah",
  "Nurlita Widyawati",
  "Syazwina Sabrina Alazri",
  "Tiva Arbangatus Zulaikha",
  "Intan Luqiana Atayayumma",
  "Salma Aqilah",
  "Aliya Salsabilla",
  "Diana Puspita Sari",
  "Gayuh Sari Utami",
  "Nila Shifa Nuzula",
  "Okta Fitriani",
  "Shal Shabila Andriani",
  "Aghnia Nasywa Dien Nuha",
  "Salsabila Zabrina Yuda",
  "Winda Juliana",
  "Maliza Suhada",
  "Tata Cahya Ratih",
  "Lydia Erna Shaferlin",
  "Nadin Nikita Putri",
  "Nurul Hidayatul Hikmah",
  "Eva Cahya Rini",
  "Rauf Amanullah",
  "Zahra Nabila",
  "Aifatul Maula",
  "Aulia Pratiwi",
  "Noviana Kusumaningsih",
  "Syifa Aura Ramadhanti",
  "Christina Aguilera",
  "Dina Qurrotu Ngaini",
  "Dwi Elsa Lestari",
  "Nabila Maharani Asngari",
  "Nurul Hidayatul Falasifah",
  "Suci Fitriyani",
  "Arifah Khoeruniyah",
  "Arifatul Munawwaroh",
  "Sa'adati",
  "Dwi Anggraeni",
  "Hafizah Adinisa",
  "Nediva Izzatul Azka",
  "Aryani Dwi Rahmawati",
  "Dwi Endah Pangesti",
  "Febryana Khaisah Sifaul Qolbu",
  "Zahra Aatiqah",
  "Al Mira Syafina Maulida",
  "Alsa Asqia",
  "Arum Syifa Saharany",
  "Dynda Bagoes Silvina",
  "Fashihatul Huda Khoyrunnisa",
  "Indah Ayu Setyaningsih",
  "Mentari Putri",
  "Meylinda Kholifathul Zana",
  "Mirza Lijana",
  "Rustiana Nur Rofikoh",
  "Ika Nurya Sabila",
  "Rostika Dewi",
  "Afra Azighah Oktar",
  "Pricel Ananda Pratama",
  "Aulya Zahra Ramadhani",
  "Intan Luqiana Atayayumma",
  "Nova Aulia Habiela",
  "Anggi Galih Cadhika",
  "Fina Salsabila Auliya Putri",
  "Salzabillah Mufidah Febriyani",
  "Vian Dwi Andika",
  "Handhika Sanny Adrian",
  "Meylins Eka Risdiyanti",
  "Mayshella Arum Wangi",
  "Safaliya Safitri",
  "Saifudin Wahid",
  "Fibian Damar Nandana",
  "Adilah",
  "Gesit Rafi Akbarramantika",
  "Winda Riyanti",
  "Chieka Pride Putri",
  "Maliza Suhada",
  "Emunabel Adiningrat",
  "Wigatiningsih",
  "Merlin Amelia Nainel",
  "Agnes Vianita",
  "Dwi Endah Pangesti",
  "Nesya Mayla",
  "Paskah Sandhya Artahsasta",
  "Alvin Rizky Oktafiansyah",
  "Muhammad Wildan Muzakkiy",
  "Rizq Maulana Mustaqiim",
  "Nabil Almuzhaffar Putra",
  "Anggara Rama Saputro",
  "Muh. Danisywar Faza Habibi",
  "Taufik Yulianto",
  "Moh. Lathif Ma'sum",
  "Triyanwar Miftahul Rizqi",
  "Didi Mulyadi",
  "Rizki Nur Rahman",
  "Daffa Nur Fakhri Rahmandika",
  "Prasetyo Wibowo",
  "Akhmad Ujang Alviansyah",
  "Darren Zayyan Wijaya",
  "Wiji Cahyo",
  "Arif Samsi Duha",
  "Shafwanilham Aderafa Ahmad",
  "Muhamad Rayyan Fikri",
  "Raflif Arkan Azqian",
  "Muhammad Alvin Febriansyah",
  "Satria Wardana Kusuma Setyawan",
  "Hazel Tsaqif Arkhab Faizin",
  "Nesa Wildan Nirwana",
  "Rafli Fardhan Sandria",
  "Raditya Gandhewa Sakti",
  "Wahyu Riyadi",
  "Daffa Rizky S",
  "Devano Brienza Lavezzi",
  "Muhamad Surya Fattah",
  "Andika Setiawan",
  "Dwiki Agus Wicaksono",
  "Tegar Wahyu Pratama",
  "Syaeful Khalim",
  "Nadif Zauma Fauzan",
  "Dian Penggalih",
  "Ahmad Miftahul Huda",
  "Sofyan",
  "Muhammad Rossi Firmansyah",
  "Fatwa Muhammad",
  "Firdaus Anang A",
  "Saeful Wahid",
  "Fibian Damar Nandana",
  "Yogi Prasetiyo",
  "Ade Iman Apriyanto",
  "Novan Bagus Subakti",
  "Fatih Dany Satriaji",
  "Reny Nur Anggraeni",
  "Sekar Fatimah",
  "Tri Indah Ayu Palupi",
  "Anggun Lavina Fajarrina",
  "Kalila Khairin Ramadhani",
  "Refani Wahyu Ningsih",
  "Ridha Yuliani",
  "Uning Nia Safitri Lestari",
  "Auliaa Lutfi Munisah",
  "Alsa Asqia",
  "Siska Rahayu",
  "Vika Dwi Azzura",
  "Nabiilah Zul Zain",
  "Safitri Nur Amalia",
  "Iva Virly Yuliana",
  "Amelia",
  "Nayla Zahra Rianjani",
  "Fendi Setiawan",
  "Surya Fahary Syahputra",
  "Dian Penggalih",
  "Muhammad Abduh Zain",
  "Rafif Sawlsa Samahita",
  "Julian Akbar",
  "Muhammad Wisnu Pamungkas",
  "Bagus Maulana Saputra",
  "Sandy Agung Pratama",
  "Muhammad Fahmi Sidik",
  "Yunus Al Ghifari",
  "Rangga Prawira Nugraha",
  "Revaldo",
  "Hanu Damar Jaya",
  "Devvan Fahri",
  "Muhammad Nur Rohman",
  "Aizam Hilmii Mufadldlol",
  "Agung Yazid Al Bustomi",
  "Maulana Galeh Satria",
  "Dwi Agus Prihantoro",
  "Ilham Dwi Kuncoro",
  "M. Nur Hakim",
  "Ghifary Arsyad Alfarez",
  "Agung Pambudi",
  "Faisal Akbar",
  "M Ghaisan Akmal",
  "Aryanto Wibowo",
  "Ikhvan Lutfianur",
  "Hafizh Naufal Fiyandika",
  "Muhamad Rayyan Fikri",
  "Hazel Tsaqif Arkhab Faizin",
  "Nafa Citra Alamsyah",
  "Umi Eriyanti",
  "Nanda Cahya Kamila",
  "Rina Agustina Arifianti",
  "Sherly Aulia Putri Effendi",
  "Silviatri Yulianti",
  "Adelina Firly",
  "Rhifa Bunga Triyanti",
  "Rohmah Nur Isnaeni",
  "Reviana Septian Rahmadani",
  "Nimas Ngulwinnisa Futuwah",
  "Anggun Dwi Safitri",
  "Tiyas Nurul 'Aini",
  "Fajar Maratussolihah",
  "Naya Arfiyani Sugesti",
  "Putri Anjani Arienza",
  "Kaila Akila Azzahra",
  "Riska Setiarini",
  "Ninik Nisarani",
  "Agil Rahmadhani",
  "Dimas Abimanyu",
  "Azizahtun Nazwa",
  "Berliana Keisky",
  "Meira Rizka Zahra",
  "Khusnun Nihayati",
  "Dewi Arum Sari",
  "A'Eni Saipem",
  "Ibtihal Juwairiyah",
  "Fatya Anisa Listianti",
  "Asiilah Farah Amalia",
  "Farah Rahman",
  "Nisfiatun Nimah",
  "Rio Bangkit Septian",
  "Almaira Ananda Fika",
  "Muhammad Raihan Hafizh Sya'bani",
  "Diana Vidya Zulfa",
  "Fitri Oktavia Sari",
  "Nadira Dwi Arista",
  "Belva Bintang Prayogatama",
  "Chieka Pride Putri",
  "Surya Fahary Syahputra",
  "Alif Nur Aditiyan",
  "Hanu Damarjaya",
  "Syifaul Mukhofifah",
  "Afif Banar Arrahman",
  "Emunabel Adiningrat",
  "Rina Agustina Arifianti",
  "Khalisha Farrasa Ramadhani",
  "Lutfiana Dwi Rahayu",
  "Safadilla Nur'aini",
  "Lutfiana Zulfia",
  "Kimi Devarian Hardiyanto",
  "Nurdina Nazala",
  "Rona Aghisna",
  "Tiara Puspa F",
  "Farand Akhmad Brianartha",
  "Faishal Latief Al Harits",
  "Indra Perdana",
  "Ashfa Annaida Ummaya",
  "Difa Marsha Amelia",
  "Farridatun Khasanah",
  "Khansa Ainun Mahya",
  "Luthfia Almeira Prasrtya",
  "Naomi Ekha Palupiningtyas Utami",
  "Anindia Aulia Zulfa",
  "Farinza Ansyida Taufika",
  "Novi Putri",
  "Aifatul Maula",
  "Ailsa Syahda Ramadani",
  "Aulia Pratiwi",
  "Dinar Husnaya",
  "Nanda Cahya Kamila",
  "Sherly Aulia Putri Effendi",
  "Angelina Suci Ramadhani",
  "Kamila Az Zahra",
  "Nabila Maharani Asngari",
  "Yesi May Lovi",
  "Anisah Husna Istiqomah",
  "Fadhilah Rahma Asyifa",
  "Farida Kapiyarsi",
  "Febrisa Heti Putri Wulandari",
  "Khusnun Nihayati",
  "Nena Tri Apriliana",
  "Aulia Wahyu Risa",
  "Desi Anggreani",
  "Dewi Cendana",
  "Diah Fitrotul 'Izzah",
  "Elva Vanesa Devina",
  "Fairuz Husna",
  "Iis Setiya Ningsih",
  "Nova Okta Rosdiana",
  "Melati Yogi Febriyanti",
  "Sakya Keisha Reena Pitra",
  "Avielle Nur Aida",
  "Dewi Arum Sari",
  "Dian Rantika Sari",
  "Firda Sari",
  "Idha Muflihatun Ngarofah",
  "Isnaeni Isma Saraswuri",
  "Julinar Riyanti",
  "Nahla Adzra Nirendra Prafista",
  "Adilla Durotul Khikmah",
  "Ikhtiara Iqomatul Haq",
  "Nabila Novita Aurellia",
  "Riska Rahmadina",
  "Dynda Bagoes Silvina",
  "Junita Dewi Hapsari",
  "Mirza Lijana",
  "Rustiana Nur Rofikoh",
  "Sri Rakhmawati Kurnianingsih",
  "Syifaaul Jannah",
  "Wirda Karisagita",
  "Aina Julia Nexsha",
  "Felita Indah Oktafitriani",
  "Shinta Aulia Nurhamidah",
  "Arba Qurrati Ainina",
  "Atikah Rafidatun Nabila",
  "Ayu Noviana Sari",
  "Difa Arini",
  "Fara Syifa Azzahra",
  "Jesica Adelia Putri",
  "Khalisa Putri Agustiyani",
  "Laudya Sri Rahayu",
  "Rizki Nur Zahira",
  "Annisa Akmalia Tsani",
  "Azkia Ramadani Soba",
  "Mayla Sari",
  "Tria Nayla Afkarina",
  "Ceryl Kahuna Vexia Putri",
  "Desi Nur Fitriyani",
  "Gita Noor Fazila",
  "Erika Winarti",
  "Erin Adita Salsabila",
  "Iva Virly Yuliana",
  "Salsabila Aila Putri",
  "Alyna Elisabet Manafe",
  "Aprilia Lestari",
  "Nadia Putri Agustin",
  "Putri Wijaya",
  "Rifqoh Alzena Ghazalah",
  "Alin Febriana",
  "Nayla Zahra Rianjani",
  "Witya Puspa Ningsih",
  "Alaina Amatus Sulthon",
  "Amellia Agustina",
  "Dealova Anindya Salsabila",
  "Devina Claudya Parwati",
  "Maula Hanum Heraldin",
  "Nathaniela Azalia Syarief",
  "Devin Kumara Adi Prihatmaja",
  "Satya Nanda Esa",
  "Livia Adiska Maulida",
  "Alya Jasmine Al Nazwa",
  "Aura Valentina",
  "Sadina Artanti",
  "Atiana Bangkit Kartikasari",
  "Naura Fadilla",
  "Sheva Angger Fadhila",
  "Nadin Nikita Putri",
  "Azizahtun Nazwa",
  "Analia Kholifatul Khasanah",
  "Naya Setyaning Wigati",
  "Khalista Alya Kinanti",
  "Violeta Satya Welova",
  "Lailani Muffaridhatus Sholihah",
  "Naafi Aliyysyah Ramadhani",
  "Nazwa Kharisma Aulia",
  "Wulan Suci Ashari",
  "Alfianah",
  "Sekar Meilani",
  "Siti Muchtarifah Ramadhani",
  "Cesha Cika Azahra",
  "Salwaliyana Mahashila",
  "Almira Mulyandari",
  "Syifaul Mukhofifah",
  "Naura Anindita Putri",
  "Pijar Padmarini",
  "Hasnah Aulia",
  "Andina Vica Meysafa",
  "Fiorenza Asmara Tungga",
  "Sa'adati",
  "Anis Murtaffingah",
  "Mahdah Nur Cahyani",
  "Farah Nahda Lestari",
  "Ikhtiara Iqomatul Haq",
  "Syifa Rizqi Apriliana",
  "Venty Ristiyana Dewi",
  "Fadhilah Nurrohmah",
  "Devansa Fawwaz Xanderchore Barus",
  "Juventia Raissa Qutratu'ain"
];

// Fungsi untuk menghasilkan data acak
function generateRandomData(nama) {
  return {
    name: nama, // Use faker.person instead of faker.name
    opinion1: faker.helpers.arrayElement(['Sangat bersih', 'Cukup bersih', 'Kurang bersih', 'Tidak bersih sama sekali']),
    opinion2: faker.helpers.arrayElement(['Tidak pernah', 'Jarang', 'Sering', 'Sangat sering']),
    opinion3: faker.helpers.arrayElement(['Tidak berdampak', 'Berdampak sedikit', 'Berdampak cukup signifikan', 'Berdampak sangat signifikan']),
    opinion4: faker.helpers.arrayElement(['Sangat bersih.', 'Cukup bersih.', 'Kurang bersih.', 'Sangat kotor.']),
    opinion5: faker.helpers.arrayElement(['Selalu kesulitan', 'Sering kesulitan', 'Kadang-kadang kesulitan', 'Tidak kesulitan sama sekali']),
    opinion6: faker.helpers.arrayElement(['Tidak ada peningkatan', 'Tidak terlalu meningkat', 'Sedikit meningkat', 'Ya, sangat meningkat']),
    opinion7: faker.helpers.arrayElement(['Tidak berdampak sama sekali.', 'Tidak terlalu berdampak.', 'Berdampak sedikit.', 'Ya, sangat berdampak.']),
    opinion8: faker.helpers.arrayElement(['Sangat tidak mencukupi', 'Kurang mencukupi', 'Cukup mencukupi', 'Sangat mencukupi']),
    opinion9: faker.helpers.arrayElement(['Sangat tidak setuju', 'Tidak setuju', 'Setuju', 'Sangat setuju']),
    opinion10: faker.helpers.arrayElement(['Tidak ada pengaruh', 'Kecil', 'Cukup besar', 'Sangat besar']),
    opinion11: faker.helpers.arrayElement(['Tidak tahu.', 'Tidak pernah.', 'Ya, sesekali.', 'Ya, secara rutin.']),
    opinion12: faker.helpers.arrayElement(['Tidak pernah membawa pulang', 'Kadang-kadang membawa pulang', 'Sering membawa pulang', 'Ya, selalu membawa pulang']),
    opinion13: faker.helpers.arrayElement(['Tidak peduli sama sekali', 'Kurang peduli', 'Tetap sama', 'Lebih peduli']),
    opinion14: faker.helpers.arrayElement(['Tidak merasa sama sekali', 'Tidak terlalu merasa', 'Cukup merasa', 'Sangat merasa']),
    opinion15: faker.helpers.arrayElement(['Tidak penting sama sekali', 'Tidak terlalu penting', 'Cukup penting', 'Sangat penting']),
    opinion16: faker.helpers.arrayElement(['Ruang kelas', 'Lorong-lorong sekolah', 'Kantin', 'Lapangan/taman']),
    opinion17: faker.helpers.arrayElement(['Sangat tidak setuju.', 'Tidak setuju.', 'Setuju.', 'Sangat setuju.']),

    opinion18: faker.helpers.arrayElement(['Tidak bersih sama sekali', 'Kurang bersih', 'Cukup bersih', 'Sangat bersih']),
    opinion19: faker.helpers.arrayElement(['Selalu', 'Sering', 'Kadang-kadang', 'Tidak sama sekali']),
    opinion20: faker.helpers.arrayElement(['Sangat sering.', 'Sering.', 'Jarang.', 'Tidak pernah.,']),
    opinion21: faker.helpers.arrayElement(['Berdampak sangat signifikan', 'Berdampak cukup signifikan', 'Berdampak sedikit', 'Tidak berdampak']),
    opinion22: faker.helpers.arrayElement(['Tidak peduli sama sekali', 'Tidak terlalu peduli', 'Sedikit lebih peduli', 'Ya, sangat peduli']),
    opinion23: faker.helpers.arrayElement(['Sangat rendah', 'Rendah', 'Cukup tinggi', 'Sangat tinggi']),
    opinion24: faker.helpers.arrayElement(['Tidak mencukupi sama sekali', 'Kurang mencukupi', 'Cukup mencukupi', 'Sangat mencukupi']),
    opinion25: faker.helpers.arrayElement(['Tidak mempengaruhi sama sekali', 'Tidak terlalu mempengaruhi', 'Ya, sedikit mempengaruhi', 'Ya, sangat mempengaruhi']),
    opinion26: faker.helpers.arrayElement(['Sangat sering,', 'Sering,', 'Jarang,', 'Tidak pernah,']),
    opinion27: faker.helpers.arrayElement(['Tidak peduli', 'Kurang tegas', 'Sama saja seperti sebelumnya', 'Lebih tegas']),
    opinion28: faker.helpers.arrayElement(['Tidak pernah`', 'Jarang`', 'Kadang-kadang`', 'Ya, sering`']),
    opinion29: faker.helpers.arrayElement(['Tidak pernah.`', 'Kadang-kadang.`', 'Sering.`', 'Selalu.`']),
    opinion30: faker.helpers.arrayElement(['Udara malah lebih segar', 'Tidak ada perubahan', 'Ya, sedikit lebih buruk', 'Ya, jauh lebih buruk']),
    opinion31: faker.helpers.arrayElement(['Tidak pernah,`', 'Jarang,`', 'Kadang-kadang,`', 'Ya, selalu,`']),
    opinion32: faker.helpers.arrayElement(['Saya tidak pernah memilah sampah', 'Membuat saya lebih jarang memilah', 'Tidak ada pengaruh', 'Membuat saya lebih rajin memilah']),
    opinion33: faker.helpers.arrayElement(['Tidak pernah..', 'Jarang..', 'Sering..', 'Sangat sering..']),
    opinion34: faker.helpers.arrayElement(['Tidak ada pengaruh.', 'Kecil.', 'Cukup besar.', 'Sangat besar.']),
  }
}

function delay(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}


async function fillGoogleForm(nama) {
  const randomData = generateRandomData(nama); // Menghasilkan data acak

  // URL Google Form yang ingin diisi
  const formUrl = 'https://forms.gle/LCxFDHMXHfoABtMw9';

  // Meluncurkan browser
  const browser = await puppeteer.launch({ headless: true }); // headless: false agar terlihat prosesnya
  const page = await browser.newPage();

  // Membuka Google Form
  await page.goto(formUrl, { waitUntil: 'networkidle2' });

  // Mengisi Nama (dengan data acak)
  await page.type('input[aria-labelledby="i1"]', randomData.name);

  // Mengisi pilihan pada pertanyaan multiple choice, dengan data acak
  await page.click(`div[data-value="${randomData.opinion1}"]`);
  await page.click(`div[data-value="${randomData.opinion2}"]`);
  await page.click(`div[data-value="${randomData.opinion3}"]`);
  await page.click(`div[data-value="${randomData.opinion4}"]`);
  await page.click(`div[data-value="${randomData.opinion5}"]`);
  await page.click(`div[data-value="${randomData.opinion6}"]`);
  await page.click(`div[data-value="${randomData.opinion7}"]`);
  await page.click(`div[data-value="${randomData.opinion8}"]`);
  await page.click(`div[data-value="${randomData.opinion9}"]`);
  await page.click(`div[data-value="${randomData.opinion10}"]`);
  await page.click(`div[data-value="${randomData.opinion11}"]`);
  await page.click(`div[data-value="${randomData.opinion12}"]`);
  await page.click(`div[data-value="${randomData.opinion13}"]`);
  await page.click(`div[data-value="${randomData.opinion14}"]`);
  await page.click(`div[data-value="${randomData.opinion15}"]`);
  await page.click(`div[data-value="${randomData.opinion16}"]`);
  await page.click(`div[data-value="${randomData.opinion17}"]`);
  //   Next Page
  await page.click(`div[class="uArJ5e UQuaGc YhQJj zo8FOc ctEux"]`);
  await page.waitForNavigation();

  await page.click(`div[data-value="${randomData.opinion18}"]`);
  await page.click(`div[data-value="${randomData.opinion19}"]`);
  await page.click(`div[data-value="${randomData.opinion20}"]`);
  await page.click(`div[data-value="${randomData.opinion21}"]`);
  await page.click(`div[data-value="${randomData.opinion22}"]`);
  await page.click(`div[data-value="${randomData.opinion23}"]`);
  await page.click(`div[data-value="${randomData.opinion24}"]`);
  await page.click(`div[data-value="${randomData.opinion25}"]`);
  await page.click(`div[data-value="${randomData.opinion26}"]`);
  await page.click(`div[data-value="${randomData.opinion27}"]`);
  await page.click(`div[data-value="${randomData.opinion28}"]`);
  await page.click(`div[data-value="${randomData.opinion29}"]`);
  await page.click(`div[data-value="${randomData.opinion30}"]`);
  await page.click(`div[data-value="${randomData.opinion31}"]`);
  await page.click(`div[data-value="${randomData.opinion32}"]`);
  await page.click(`div[data-value="${randomData.opinion33}"]`);
  await page.click(`div[data-value="${randomData.opinion34}"]`);


  await page.click(`div[class="uArJ5e UQuaGc Y5sE8d VkkpIf QvWxOd"]`);
  await delay(5000);

  // Lanjutkan untuk pertanyaan lainnya dengan cara serupa...

  // Mengirimkan form
  //   await page.click('span[class="appsMaterialWizButtonPaperbuttonLabel"]');

  // Tunggu beberapa detik sebelum menutup browser
  //   await page.waitForTimeout(5000);

  // Tutup browser
  await browser.close();
}

(async () => {
  for (let i = 0; i < 5; i++) {
    const nama = namaPendek[i];
    await fillGoogleForm(nama);
    console.log('Done: ' + nama)
  }

})();
